#!/bin/bash

GRAPHITE=<Graphite server name>
PORT=2003
HOSTNAME=`hostname | cut -d. -f1`

Month=`date +%b`
Day=`date +%_d`

NumberOfLogins=`cat /var/log/secure | grep -v "session opened for user root" | grep "session opened for user" | grep "$Month $Day" | wc -l`

echo $NumberOfLogins

echo "$HOSTNAME.logins.count $NumberOfLogins `date +%s`" | nc $GRAPHITE $PORT
